name: mmoRace
version: ${releaseVersion}.${buildNumber}
description: Provides an API for controlling race.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Race.MMORace
depend: [Spout, mmoCore]

permissions:
    mmo.race.self.set:
        description: Allowed to set their own race
        default: true
    mmo.race.self.change:
        description: Allowed to change their own race
        default: op
    mmo.race.all.set:
        description: Allowed to set anyone's race (including own)
        default: op
    mmo.race.all.change:
        description: Allowed to change anyone's race (including own)
        default: op
